FROM maven:3.8.5-open-jdk-17 AS build

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim

COPY --from=build /target/jobportal-0.0.1-SNAPSHOT.jar jobportal.jar

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "jobportal.jar" ]